package commons

const STATUS_OK_MESSAGE = "OK"
const STATUS_BAD_REQUEST_MESSAGE = "status_bad_request"
const USER_SYSTEM = "SYSTEM"
const AGE_OLDER_CLIENT = 55

const QUESTION_FOR_VEHICLE_ZEROKM = "OBLIGATORY_ZEROKM"
const DEFAULT_YES = "Y"
const DEFAULT_NO = "N"
const ZERO = 0

const QUESTION_TYPE_IMAGE = "IMAGE"
const QUESTION_TYPE_DESCRIPTION = "DESCRIPTION"
const QUESTION_TYPE_SINGLE_CHOICE = "SINGLE_CHOICE"
const QUESTION_TYPE_MULTIPLE_CHOICE = "MULTIPLE_CHOICE"

const CATEGORY_EVALUATION = "EVALUATION"
const CATEGORY_REQUIREMENTS = "REQUIREMENT"
